exclude: 'migrations|.git|.tox'
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0  # Use the revision sha / tag you want to point at
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/prospector
    rev: 1.3.1
    hooks:
      - id: prospector
        language: system

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
