"""用户增加激活状态

Revision ID: 2c831198c168
Revises: 62695de8939b
Create Date: 2020-08-31 18:20:54.520627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c831198c168"
down_revision = "62695de8939b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eva_identity", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eva_identity", "is_active")
    # ### end Alembic commands ###
